# Generated by Django 4.0 on 2021-12-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_job_alter_candidate_id_alter_candidate_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skill',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
