# Generated by Django 4.0 on 2021-12-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_job_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='phone',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
